### ISSUE TITLE
API Gateway

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [mjhea0/microservice-movies#1]
Hi!
Wouldn't it be nice to have some API gateway in front of your microservices?
This way your microservices infrastructure would be invisible for consumers (the React App) and you would expose a single service to the world, which internally would communicate with your microservices.
I have doubts if it would be better to use a simple reverse proxy or implement an api gateway myself (in JS or some other language)
Do you have any advices on this subject?

**Comment by mjhea0** [comment]
Check out https://www.nginx.com/blog/building-microservices-using-an-api-gateway/
